### ISSUE TITLE
Spec redefines or possibly conflicts with fetch

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp#20]
There seems to be a lot overlap with [fetch](http://fetch.spec.whatwg.org/). Fetch defines how HTTP(S) resources are obtained in the platform. Please avoid redefining how client and servers interact over HTTP or you risk introducing security issues.

**Comment by iherman** [comment]
(Just as an administrative note: this is related to the [separate thread on web manifests](https://github.com/w3c/manifest/issues/471#issuecomment-227997939))

**Comment by iherman** [comment]
Thanks @marcoscaceres, we will have to look at this (as well...) if and when this work becomes input for a WG material (at the moment, this is only an IG).

**Comment by marcoscaceres** [comment]
It's interesting stuff. Happy to answer any web dev/js questions ... or questions about any upcoming browser tech.

**Comment by iherman** [comment]
> On 23 Jun 2016, at 12:07, Marcos Cáceres notifications@github.com wrote:
> 
> It's interesting stuff. Happy to answer any web dev/js questions ... or questions about any upcoming browser tech.

Thanks for your interest!
