### ISSUE TITLE
Paragraph on the broader Web Platform?

### ISSUE THREAD

**Issue by iherman** [w3c/dpub-pwp#23]
The current document includes a paragraph (in section 2) saying

> The broader Web Platform can also be considered to be at a tipping point…

It may not be appropriate in this document to make general statements on the Web platform, even if it is relevant to DPUB. It may also start unnecessary discussions (unnecessary for the topic at hand, that is) which may side-track the necessary discussions around PWP proper.

I would propose to replace this paragraph by a text emphasizing the advantages that the traditional Web may gain by bringing the publishing community closer (some of these texts were around in earlier versions of this document, but part of the use cases that are now to be removed).

**Comment by BorisAnthony** [comment]
+1

**Comment by iherman** [comment]
Done in https://github.com/w3c/dpub-pwp/commit/e8a57c9c3cbb3c3c31493ee256a8683598fddff3
