### ISSUE TITLE
Why "(Packaged)" in the title?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/dpub-pwp#27]
It seems a bit cumbersome to be explaining the states a web publication might be in in the title.

I get that the parentheses mean a web publication might sometimes be packaged, but that's only because I already know what this work is about. If I didn't, I'd probably start to wonder if that was a placeholder or something (which I admit I sort of did having been overwhelmed with epub for the last half year).

Why not just focus on the product being created -- the web publication -- and leave the packaging/portability of that document for the body? Not to go all marketing on you, but it's a much simpler and more powerful name without the parentheses.

If you absolutely need to explain as early as possible that the publication can be packaged, too, a subtitle might be better.

And just to really nitpick, does "for the Open Web Platform" really add anything, since they're called "Web" publications?

**Comment by dauwhe** [comment]
I think "Web Publications" is a perfectly cromulent title.

**Comment by iherman** [comment]
- I do not have a problem using "Web Publications" in the title, but should then look, with a fresh eye, on whether the packaged aspect is clear enough for readers like publishers who may need those packages…
- The "OWP" is some sort of a W3C terminology. I realize it is awkward here and there and we may have to go through the text to see whether its usage is always justified

**Comment by iherman** [comment]
Close by virtue of PR #30
