### ISSUE TITLE
Various minor nits

### ISSUE THREAD

**Issue by mattgarrish** [w3c/dpub-pwp#28]
Not sure if this document is ready for review, but I thought I'd at least mention a few non-technical items I noticed while skimming it:

- Wouldn't it make sense to group sections 1, 2 and 3 under a common heading, like "Introduction"?
- "Some Technical Challenges" - "Some" is unnecessary.
- "Profiling PWP-s?" - Drop the question mark.
- "EPUB4 as PWP" - I don't understand the heading given that there is no epub 4. Perhaps something like "Evolutionary Objective" would be more appropriate, since it talks about being a compatible evolution of epub 3.
- Headings drift from title case to sentence case in places
- Is there really any value to the first paragraph of the quoted text in the abstract? (i.e., are people really unclear what a book is?) I'd suggest keep it short and sweet and only include the more apt second paragraph.
- In 1.1, there's 'webpages' and 'websites', but elsewhere 'Web page' and 'Web site'.
- I can't recall seeing acronyms pluralized with hyphens before (API-s, WP-s and PWP-s), but maybe that's just me.

**Comment by dauwhe** [comment]
Agree, except I think we should keep all of Hugh's quote. I think it helps define the scope of our work, and provides a foundation for distinguishing publications from other web content.

**Comment by mattgarrish** [comment]
But books are only one aspect of what can be covered, right? The abstract comes off a bit schizophrenic as it starts completely book-centric with the quote and then immediately generalizes away to publications.

It would be better to have a definition of a publication than a book, but reductionist attempts at such things invariably fall short.

**Comment by BorisAnthony** [comment]
The point of Hugh's quote is to outline an abstract definition of how we know and value printed publications. If we read the definition without getting all stuck on "not just books!", we see it works for our purposes.

Such abstractions are a) not meant to be taken literally and b) serve the purpose of setting a context. This is why it is a quote and it is added at the very top of the document.

The point is we need this format to reify notions of boundedness, portability, have-ability… while also adopting the Web's universal accessibility and addressability.

**Comment by iherman** [comment]
Taken the history into account, the version that is currently up there requires a fairly thorough rewrite. At the moment, what happened was to take the old document and reshuffle the sections with some minimal changes to along the lines of a new organization (along the lines of the newly reorganized UCR), with some texts taken over from the UCR. We are planning to have a discussion on Monday on the telco for a series of more thorough changes. Which means that many of the points may become moot...

One specific point, though: I personally believe that Hugh's quote sets the scene in a nice way and I am in favour of keeping it, though if the majority of the group wants to remove it I will not lie down on the road. That being said, we certainly have to make it clear(er) that PWP is not only for books…

**Comment by TzviyaSiegman** [comment]
@mattgarrish, taking @dauwhe and @iherman's comments into account, feel free to edit the document in a branch or PR. Thanks for nitpicking so well.

**Comment by mattgarrish** [comment]
Ya, I'm not going to draw this out; I just don't see what the rest of you claim to. That the web and print can learn from each other is an intriguing intro, but the supposed differentiation of book content just falls flat for me.

**Comment by TzviyaSiegman** [comment]
I do hear where Matt is coming from. Opening the document with a statement about books might defeat our #notjustbooks position more than we intend. However, Hugh's quote has helped many understand that we are trying to accomplish something beyond a series of linked web pages. Do we take this out of the abstract? Suggestions welcome.

**Comment by mattgarrish** [comment]
Or maybe integrate it to lose the book-iness? My best five-minute rewrite would be to take a path like this:

> “Books can learn from the Web how to be bounded, but open.
> The Web can learn from books how to be open, but bounded.”
> 
> Hugh McGuire, Medium, April 2016
> 
> A publication represents “an internally complete representation of an idea, or set of ideas; emotion or set of emotions”. The traditional Web model of a loosely connected set of pages does not capture the connected and bounded nature of such publications in the same way that print does, however, nor the desire to make such documents portable beyond their host sites. Publications, from corporate memos to newsletters to electronic books to scholarly journal articles, need the same treatment given to the more common forms of Web pages available today, which requires addressing the current shortcomings.
> 
> This document describes the various use cases highlighting the problems users and publishers face when these publications are to be used in a digital, Web environment. This document introduces (Packaged) Web Publications, a vision for the future of digital publishing that is based on a fully native representation of documents within the Open Web Platform. (Packaged) Web Publications achieve full convergence between online and offline/portable document publishing: publishers and users won't need to choose one or the other, but can switch between them dynamically, at will. Authors can concentrate on the way they intend to transmit their ideas and emotions, without having to deal with the specificities of a particular format.

**Comment by iherman** [comment]
I like it…

A minor thing that this text refers to the use cases which is done in another document, but that is a detail…

Ivan

**Comment by iherman** [comment]
Separated the issue on the quote in the abstract into #31, and closed the issue because all the other comments have been dealt with in #30.
