### ISSUE TITLE
Add more about manifests

### ISSUE THREAD

**Issue by iherman** [w3c/dpub-pwp#9]
Manifests _may_ be a requirement for PWP-s to describe the content of the package (ie, the resources it contains) as well as a possible remapping of URL-s. Maybe worth its separate section?

**Comment by iherman** [comment]
Actually it was a separate section, but just badly chosen section title; but some rewrite is still necessary.

**Comment by dret** [comment]
https://github.com/w3c/manifest/issues/452 is about the webapp manifest draft and the possibility of using this as a starting point for how PWP manifests could work.

**Comment by iherman** [comment]
Forgot to close, was done a while ago...
